#!/usr/bin/env python3
"""Build the served CSS/JS bundles from their component and page sources.

Sources (edit these):  public_html/assets/css/src/**.css   public_html/assets/js/src/**.js
Bundles (generated):   public_html/assets/css/hg-site.css, hg-ui.css   public_html/assets/js/hg-site.js, hg-ui.js

The pages keep loading the same four files, so HTML never changes when assets are rebuilt.
Order matters (the cascade): the lists below are the order of concatenation.
Usage: python3 tools/build_assets.py [--check]   (--check: fail if a bundle is out of date)
"""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
A = os.path.join(ROOT, 'public_html', 'assets')

CSS = {
    # GLOBAL SHELL (loaded first): tokens, icons, support widget, cookie consent, footer
    'hg-site.css': ['tokens', 'components/icons', 'components/support-widget', 'components/cookie-consent', 'components/footer'],
    # Design-system base, shared content components, shell (header/nav), then page modules
    'hg-ui.css': ['global', 'components/content', 'components/utility-bar', 'components/header', 'components/holiday-search',
                  'components/navigation', 'components/mega-menu', 'components/login-dialog',
                  'pages/homepage', 'pages/search-results', 'pages/tour-detail', 'pages/itinerary', 'pages/contact',
                  'pages/travel-guide', 'pages/people', 'pages/policy', 'pages/customized-holidays'],
}
JS = {}  # filled below when assets/js/src exists (see JS_ORDER files)
JS_ORDER = os.path.join(A, 'js', 'src', 'ORDER')

BANNER_CSS = '/* GENERATED by tools/build_assets.py from assets/css/src/ (%s). Do not edit this file: edit the sources and rebuild. */\n'


def build_css():
    out = {}
    for bundle, parts in CSS.items():
        body = [BANNER_CSS % ', '.join(p + '.css' for p in parts)]
        for p in parts:
            src = open(os.path.join(A, 'css', 'src', p + '.css'), encoding='utf-8').read()
            body.append('\n/* ===== src/%s.css ===== */\n' % p + src.rstrip('\n') + '\n')
        out[os.path.join(A, 'css', bundle)] = ''.join(body)
    return out


def build_js():
    """JS bundles are an exact concatenation of their ordered source chunks (byte-identical output)."""
    out = {}
    if not os.path.exists(JS_ORDER):
        return out
    bundle = None
    for line in open(JS_ORDER, encoding='utf-8'):
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if line.endswith(':'):
            bundle = line[:-1]; out[os.path.join(A, 'js', bundle)] = ''
        else:
            out[os.path.join(A, 'js', bundle)] += open(os.path.join(A, 'js', 'src', line), encoding='utf-8').read()
    return out


def main():
    check = '--check' in sys.argv
    stale = []
    for path, content in {**build_css(), **build_js()}.items():
        cur = open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if cur != content:
            stale.append(os.path.relpath(path, ROOT))
            if not check:
                open(path, 'w', encoding='utf-8').write(content)
    if check and stale:
        sys.exit('out of date (run tools/build_assets.py): ' + ', '.join(stale))
    print(('checked' if check else 'built') + ': ' + (', '.join(stale) if stale else 'all bundles up to date'))


if __name__ == '__main__':
    main()
